/* tslint:disable */
/* eslint-disable */
/**
 * NTUB-AUTH-SERVER API
 * 北商大認證伺服器 API
 *
 * The version of the OpenAPI document: v1
 * Contact: 11146001@ntub.edu.tw
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

